sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t synthesis77/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true synthesis77/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-707785140749"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_Access_Key
    secret_access_key: $AWS_SECRET_KEY
