sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t synthesis77/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true synthesis77/docker-react npm run test
